import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const typeWriter = localFont({
  src: "./fonts/typeWriter.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body className={`${typeWriter.className} min-h-full flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
